name: ${project.artifactId}
version: ${project.version}
author: OhBlihv
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
softdepend: [SocketAPI]
commands:
    ${project.artifactId}: